### ISSUE TITLE
How to convert Chord Organ into a Radio Music?

### ISSUE THREAD

**Issue by dimleaffall** [TomWhitwell/RM_Chorder#17]
I have no idea about programming or "Teensy"(?)  How would I go about converting the Chord Organ into a Radio Music?  Thank you

**Comment by TomWhitwell** [comment]
@dimleaffall where did you buy your Radio Music?

**Comment by dimleaffall** [comment]
I have a chord organ which I bought from a guy who built it from a kit.

**Comment by TomWhitwell** [comment]
The instructions are all here: 

https://github.com/TomWhitwell/RadioMusic/wiki/Preparing-the-Teensy

I’m sure the person who sold you your module can help
