### ISSUE TITLE
Chord organ stops working after some time

### ISSUE THREAD

**Issue by fxwiegand** [TomWhitwell/RM_Chorder#22]
Hello @TomWhitwell,
i am experiencing weird problems with my chord organ. When i power it on the module works perfect for some time (1-2 minutes) and then stops outputting audio. It seems like the controls still work because the leds still light accordingly to button presses and knob turns. I attached a video of the behavior of the module.

https://user-images.githubusercontent.com/39430842/140789027-beb73f12-4818-4782-8a81-eae4fa96e487.mp4

**Comment by TomWhitwell** [comment]
Hey, sorry to hear that - could possibly be a very extreme version of this: https://github.com/TomWhitwell/RadioMusic/issues/70 so easily fixed with a 100k resistor

**Comment by fxwiegand** [comment]
Thanks a lot for the fast answer and pointing me in the right direction! Put a 100k resistor on and its been running for 10 minutes now without any problems. Would it make sense to add this problem [here](https://github.com/TomWhitwell/RadioMusic/wiki/Troubleshooting-the-Radio-Music-module) or i am just not finding it? Anyways thanks again for your help and the awesome modules!
