### ISSUE TITLE
Can't seem to access the additional waveforms

### ISSUE THREAD

**Issue by klendroid** [TomWhitwell/RM_Chorder#3]
Hi there! I just installed the new firmware (I think), but I can't seem to access the two additional pages of waveforms. I checked that I wanted the waveforms on the firmware page, downloaded the firmware, loaded it onto the module with the teensy-program (it says that it's got 0.5beta installed when I click the teensy button on the module). Pressed the program and reboot, everything went OK, it seemed. I did not upload the config file on the sd-card though, but it appears that's not necessary unless I want to change the chords. Right? I should be able to access the additional waveforms just by pressing the button on the module, right?

Any idea what might be wrong here?

**Comment by Normalised** [comment]
You have to change the config file. The extra waves (and other options like stacking, glide and note range) are all set in the configuration.

Sorry, we should make this clearer.

**Comment by klendroid** [comment]
Ok, great, thanks for the extremely quick reply! :)
