### ISSUE TITLE
Extra root note sounding on all chords

### ISSUE THREAD

**Issue by Quincas** [TomWhitwell/RM_Chorder#5]
Hi Tom!
Just installed the new firmware and I love the new waves and the better 1v/oct response. A couple of things though.

The cv response is not quite perfect. Using my Keystep's pitch CV out, some notes are off by a half step, some don't get recognized. Only the next to highest octave tracks correctly. I left the custom option off in the ini file. Should I set that to something? Is there a digical procedure I don't know about?

The other thing is that I actually programmed a whole chord progression, including root movements, but now there's a constant low "root" note, which in my case isn't the real root. I think it's important to be able to program chords that don't have the root at all, or have a transposed root relative to the "0" note.

Anyways, great module, thanks :)

best
Q

**Comment by Normalised** [comment]
1. CV Response

You can generate a config on this page : 

http://polyfather.com/chord_organ/

and change the 'Root CV Range', for some users a range of 40 works well. Or you can hand edit the file and add a line with

!RANGE 40

2. Constant low note.

This is a bug in the config reader. There is a fix you can try in the latest beta version of the firmware available here : http://polyfather.com/chord_organ/Chord-Organ.0.6.zip

The 0.6 firmware also supports scala tuning files if thats something you might be interested in :)

More info on this muff wigglers thread : 

https://www.muffwiggler.com/forum/viewtopic.php?t=177939&postdays=0&postorder=asc&start=75

Let me know how you get on.

**Comment by Quincas** [comment]
Ah, excellent, thank you! Range 40 gives me the first octave in tune, then goes off again, I'll experiment further to find the right number for my unit.
The new firmware did fix the constant low note, thanks.
and yes, I'm a microtonalist and scala file support is very exciting to me!  
Awesome, thanks again!
Cheers

**Comment by Normalised** [comment]
I'd be really interested to hear in what way it goes off, is the chord organ pitching too low or too high once you get past the first octave and is it consistent as you go up the range? any information is useful thanks :)
