### ISSUE TITLE
possibility of reloading settings at SD card insert

### ISSUE THREAD

**Issue by eeweegh** [TomWhitwell/RM_Chorder#7]
Hi there,

I noticed that my Chord Organ suffers from the same issue as my Radio Music, in that it fails to boot up properly when I apply power to the case (a Doepfer LC6, with a PSU3) with an SD card installed.

That would not be so bad, except that the Chord Organ starts up without an SD card in its default mode, then ignores card inserts, meaning I don't get my custom settings from the card (like extra wavetables).

Radio Music does reset correctly when I insert an SD card - maybe this could be put in the Chord Organ code as well?

Kind regards, erik.

**Comment by Normalised** [comment]
The option to run Chord Organ without an SD means that the only way of doing hot-swap, which is trying to read from the card regularly, won't work.
So I think the only option on the software side is to build 2 versions, 1 where SD is required and one where it is not.

Have you tried asking on the muff wiggler DIY forum about the power up / boot issue?

**Comment by eeweegh** [comment]
I see - I was assuming that there would be some interrupt from the card when inserted (I have yet to get familiar with the teensy hardware/software environment, so still a bit naive).

Yes, I added comments on the Radio Music issue list on GitHub, and on MuffWiggler's. Everybody agrees that there's a problem, but nobody seems to know the real cause, or a definite workaround. For Radio Music, leaving the SD card out while powering up seems to help in most cases (suggesting that the 5v regulator is taxed too much at startup if you add the SD power consumption to the Teensy booting and the LEDs). I've been considering adding a reset button, but [a] I lack confirmation that that is actually going to work, and [b] it's a nasty solder thing on the back of the teensy board. Scared of ruining it, and having nothing left :-).

**Comment by eeweegh** [comment]
OK, looked at the code, and I understand your explanation. Radio Music calls a pseudo hot swap routine when it fails to read further data, so it's rather detecting a card removal than a card insert.

Maybe abuse longPress (or *reallyLongPress*) to trigger a reboot?

**Comment by Normalised** [comment]
Yeah, im happy for something like a 5 second really long press to cause a reboot.

You're not going to accidentally hold the button down for that long :)

**Comment by eeweegh** [comment]
thanks! Looking forward to that. Let me know if you want me to beta test.

**Comment by Normalised** [comment]
Ok, try this :

http://polyfather.com/chord_organ/Chord_Organ_SD_Required.zip

**Comment by eeweegh** [comment]
hmm, no - can't get it to reboot. The only thing that happens is that it switches between normal and stacked mode. Tried holding down for several values from 5 to 30s (where I was expecting that anything above 5s would reset).

**Comment by Normalised** [comment]
Sorry, I didn't actually explain what this version does :) 

This one doesn't do long press to reboot, but instead keeps cycling at boot until an SD card is inserted, rather than starting without a card.

**Comment by eeweegh** [comment]
That explains - I can confirm it does that indeed (and so far also powering up correctly, without the SD card inserted).
Does this build mean you're sticking to two separate builds, or is it just a test build towards the long press in a single build?

**Comment by Normalised** [comment]
Here's a new build :

A: SD Card NOT required at boot
B: Reboot with long press (5 secs). The top 4 leds will light when its going to reboot.

http://polyfather.com/chord_organ/Chord_Organ_LongPressReboot.zip

**Comment by eeweegh** [comment]
hmm, now I've lost the option to swap between stacked and normal mode (I guess anything between 1s and 5s) - it seems to reset after way shorter than 5s.

**Comment by Normalised** [comment]
Youre right. I'll fix that.

**Comment by Normalised** [comment]
Download it again, same link.

One thing, at the moment the stack switch only occurs when the button is released but the reboot happens whilst the button is held.

I think i'll change it so that stack switch also occurs whilst held so you know when its long enough :)

**Comment by eeweegh** [comment]
That seems to work just fine :-) Thank you very much for the quick intervention!

I fully agree about the button down, if only because my button is a bit dodgy, and it only really works if you click on it from a particular angle :-)

**Comment by Normalised** [comment]
Great. I'll close this now. Anyone else with the same problem can use that build until the next release goes up.
