### ISSUE TITLE
Question about regulating output gain

### ISSUE THREAD

**Issue by cristianvogel** [TomWhitwell/RM_Chorder#9]
Hi. Thanks for this great project.

In general use I find the audio output to be too high, and can easily cause clipping. How could I lower output gain in the code?

**Comment by TomWhitwell** [comment]
Hi, Have you tried adjusting the trimmer on the back of the module to reduce the gain?

**Comment by cristianvogel** [comment]
Actually no... I will do that, but I have also added a couple of my own wavetables and they have different levels, so I wondered if I could assign a different level to each wave in the code?

**Comment by TomWhitwell** [comment]
The gains are set in lines 300,301 where the individual note waveforms are mixed together - you can see how the teensy audio tool works here: https://www.pjrc.com/teensy/gui/
You could write something to set different levels for different waves with those mixer values - or I don't know if there's a way to reduce the amplitude of the wave by editing the wavetable itself?

**Comment by Normalised** [comment]
With the latest firmware code in the develop branch there are settings for gain per wave type.

Its line 86 here : https://github.com/TomWhitwell/Chord-Organ/blob/develop/Chord-Organ/AudioEngine.h

In the waveformAmp array. First 4 are the 'standard' wave types, the other 8 are the wavetables.
